
// This file has been generated by the GUI designer. Do not modify.
namespace app_contable
{
	public partial class Gestion_de_usuarios_y_roles
	{
		private global::Gtk.VBox vbox15;

		private global::Gtk.HBox hbox16;

		private global::Gtk.Alignment alignment4;

		private global::Gtk.VBox vbox20;

		private global::Gtk.Label label32;

		private global::Gtk.HBox hbox28;

		private global::Gtk.HBox hbox29;

		private global::Gtk.Alignment alignment13;

		private global::Gtk.Button button7;

		private global::Gtk.HBox hbox22;

		private global::Gtk.Label label30;

		private global::Gtk.HBox hbox24;

		private global::Gtk.Entry entry21;

		private global::Gtk.Button button6;

		private global::Gtk.Label label31;

		private global::Gtk.HBox hbox23;

		private global::Gtk.Entry entry22;

		private global::Gtk.Button button5;

		private global::Gtk.HBox hbox21;

		private global::Gtk.HBox hbox25;

		private global::Gtk.HBox hbox26;

		private global::Gtk.HBox hbox27;

		private global::Gtk.Alignment alignment10;

		private global::Gtk.Alignment alignment11;

		private global::Gtk.Label label29;

		private global::Gtk.Alignment alignment9;

		private global::Gtk.Alignment alignment8;

		private global::Gtk.Alignment alignment7;

		private global::Gtk.Alignment alignment6;

		private global::Gtk.HBox hbox18;

		private global::Gtk.VBox vbox16;

		private global::Gtk.VBox vbox19;

		private global::Gtk.Label label22;

		private global::Gtk.Label label23;

		private global::Gtk.Label label24;

		private global::Gtk.Button button2;

		private global::Gtk.VBox vbox17;

		private global::Gtk.VBox vbox18;

		private global::Gtk.Entry entry20;

		private global::Gtk.ComboBox combobox1;

		private global::Gtk.ComboBox combobox2;

		private global::Gtk.HBox hbox20;

		private global::Gtk.Button button3;

		private global::Gtk.Button button4;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView treeview4;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget app_contable.Gestion_de_usuarios_y_roles
			this.Name = "app_contable.Gestion_de_usuarios_y_roles";
			this.Title = global::Mono.Unix.Catalog.GetString("Gestion de usuarios y roles");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child app_contable.Gestion_de_usuarios_y_roles.Gtk.Container+ContainerChild
			this.vbox15 = new global::Gtk.VBox();
			this.vbox15.Name = "vbox15";
			this.vbox15.Spacing = 6;
			// Container child vbox15.Gtk.Box+BoxChild
			this.hbox16 = new global::Gtk.HBox();
			this.hbox16.Name = "hbox16";
			this.hbox16.Spacing = 6;
			// Container child hbox16.Gtk.Box+BoxChild
			this.alignment4 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment4.Name = "alignment4";
			// Container child alignment4.Gtk.Container+ContainerChild
			this.vbox20 = new global::Gtk.VBox();
			this.vbox20.Name = "vbox20";
			this.vbox20.Spacing = 6;
			// Container child vbox20.Gtk.Box+BoxChild
			this.label32 = new global::Gtk.Label();
			this.label32.Name = "label32";
			this.label32.LabelProp = global::Mono.Unix.Catalog.GetString("Gestionamiento de usuarios y roles");
			this.vbox20.Add(this.label32);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox20[this.label32]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox20.Gtk.Box+BoxChild
			this.hbox28 = new global::Gtk.HBox();
			this.hbox28.Name = "hbox28";
			this.hbox28.Spacing = 6;
			// Container child hbox28.Gtk.Box+BoxChild
			this.hbox29 = new global::Gtk.HBox();
			this.hbox29.Name = "hbox29";
			this.hbox29.Spacing = 6;
			// Container child hbox29.Gtk.Box+BoxChild
			this.alignment13 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment13.Name = "alignment13";
			this.hbox29.Add(this.alignment13);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox29[this.alignment13]));
			w2.Position = 0;
			// Container child hbox29.Gtk.Box+BoxChild
			this.button7 = new global::Gtk.Button();
			this.button7.CanFocus = true;
			this.button7.Name = "button7";
			this.button7.UseUnderline = true;
			this.button7.Label = global::Mono.Unix.Catalog.GetString("Volver");
			this.hbox29.Add(this.button7);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox29[this.button7]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			this.hbox28.Add(this.hbox29);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox28[this.hbox29]));
			w4.Position = 0;
			this.vbox20.Add(this.hbox28);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox20[this.hbox28]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox20.Gtk.Box+BoxChild
			this.hbox22 = new global::Gtk.HBox();
			this.hbox22.Name = "hbox22";
			this.hbox22.Spacing = 6;
			// Container child hbox22.Gtk.Box+BoxChild
			this.label30 = new global::Gtk.Label();
			this.label30.Name = "label30";
			this.label30.LabelProp = global::Mono.Unix.Catalog.GetString("Buscar por ID");
			this.hbox22.Add(this.label30);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox22[this.label30]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox22.Gtk.Box+BoxChild
			this.hbox24 = new global::Gtk.HBox();
			this.hbox24.Name = "hbox24";
			this.hbox24.Spacing = 6;
			// Container child hbox24.Gtk.Box+BoxChild
			this.entry21 = new global::Gtk.Entry();
			this.entry21.CanFocus = true;
			this.entry21.Name = "entry21";
			this.entry21.IsEditable = true;
			this.entry21.InvisibleChar = '•';
			this.hbox24.Add(this.entry21);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox24[this.entry21]));
			w7.Position = 0;
			// Container child hbox24.Gtk.Box+BoxChild
			this.button6 = new global::Gtk.Button();
			this.button6.CanFocus = true;
			this.button6.Name = "button6";
			this.button6.UseUnderline = true;
			this.button6.Label = global::Mono.Unix.Catalog.GetString("Buscar");
			this.hbox24.Add(this.button6);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox24[this.button6]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox24.Gtk.Box+BoxChild
			this.label31 = new global::Gtk.Label();
			this.label31.Name = "label31";
			this.label31.LabelProp = global::Mono.Unix.Catalog.GetString("Buscar por ID usuario");
			this.hbox24.Add(this.label31);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox24[this.label31]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			this.hbox22.Add(this.hbox24);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox22[this.hbox24]));
			w10.Position = 1;
			// Container child hbox22.Gtk.Box+BoxChild
			this.hbox23 = new global::Gtk.HBox();
			this.hbox23.Name = "hbox23";
			this.hbox23.Spacing = 6;
			// Container child hbox23.Gtk.Box+BoxChild
			this.entry22 = new global::Gtk.Entry();
			this.entry22.CanFocus = true;
			this.entry22.Name = "entry22";
			this.entry22.IsEditable = true;
			this.entry22.InvisibleChar = '•';
			this.hbox23.Add(this.entry22);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox23[this.entry22]));
			w11.Position = 0;
			// Container child hbox23.Gtk.Box+BoxChild
			this.button5 = new global::Gtk.Button();
			this.button5.CanFocus = true;
			this.button5.Name = "button5";
			this.button5.UseUnderline = true;
			this.button5.Label = global::Mono.Unix.Catalog.GetString("Buscar");
			this.hbox23.Add(this.button5);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox23[this.button5]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			this.hbox22.Add(this.hbox23);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox22[this.hbox23]));
			w13.Position = 2;
			this.vbox20.Add(this.hbox22);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox20[this.hbox22]));
			w14.Position = 2;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox20.Gtk.Box+BoxChild
			this.hbox21 = new global::Gtk.HBox();
			this.hbox21.Name = "hbox21";
			this.hbox21.Spacing = 6;
			// Container child hbox21.Gtk.Box+BoxChild
			this.hbox25 = new global::Gtk.HBox();
			this.hbox25.Name = "hbox25";
			this.hbox25.Spacing = 6;
			// Container child hbox25.Gtk.Box+BoxChild
			this.hbox26 = new global::Gtk.HBox();
			this.hbox26.Name = "hbox26";
			this.hbox26.Spacing = 6;
			// Container child hbox26.Gtk.Box+BoxChild
			this.hbox27 = new global::Gtk.HBox();
			this.hbox27.Name = "hbox27";
			this.hbox27.Spacing = 6;
			// Container child hbox27.Gtk.Box+BoxChild
			this.alignment10 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment10.Name = "alignment10";
			this.hbox27.Add(this.alignment10);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox27[this.alignment10]));
			w15.Position = 0;
			// Container child hbox27.Gtk.Box+BoxChild
			this.alignment11 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment11.Name = "alignment11";
			this.hbox27.Add(this.alignment11);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox27[this.alignment11]));
			w16.Position = 1;
			// Container child hbox27.Gtk.Box+BoxChild
			this.label29 = new global::Gtk.Label();
			this.label29.Name = "label29";
			this.label29.LabelProp = global::Mono.Unix.Catalog.GetString("Datos del usuario y su rol");
			this.hbox27.Add(this.label29);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox27[this.label29]));
			w17.Position = 2;
			w17.Expand = false;
			w17.Fill = false;
			this.hbox26.Add(this.hbox27);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox26[this.hbox27]));
			w18.Position = 0;
			// Container child hbox26.Gtk.Box+BoxChild
			this.alignment9 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment9.Name = "alignment9";
			this.hbox26.Add(this.alignment9);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox26[this.alignment9]));
			w19.Position = 1;
			// Container child hbox26.Gtk.Box+BoxChild
			this.alignment8 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment8.Name = "alignment8";
			this.hbox26.Add(this.alignment8);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox26[this.alignment8]));
			w20.Position = 2;
			this.hbox25.Add(this.hbox26);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox25[this.hbox26]));
			w21.Position = 0;
			// Container child hbox25.Gtk.Box+BoxChild
			this.alignment7 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment7.Name = "alignment7";
			this.hbox25.Add(this.alignment7);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox25[this.alignment7]));
			w22.Position = 1;
			// Container child hbox25.Gtk.Box+BoxChild
			this.alignment6 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment6.Name = "alignment6";
			this.hbox25.Add(this.alignment6);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox25[this.alignment6]));
			w23.Position = 2;
			this.hbox21.Add(this.hbox25);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox21[this.hbox25]));
			w24.Position = 0;
			this.vbox20.Add(this.hbox21);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox20[this.hbox21]));
			w25.Position = 3;
			w25.Expand = false;
			w25.Fill = false;
			this.alignment4.Add(this.vbox20);
			this.hbox16.Add(this.alignment4);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.alignment4]));
			w27.Position = 0;
			w27.Expand = false;
			w27.Fill = false;
			this.vbox15.Add(this.hbox16);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox15[this.hbox16]));
			w28.Position = 0;
			w28.Expand = false;
			w28.Fill = false;
			// Container child vbox15.Gtk.Box+BoxChild
			this.hbox18 = new global::Gtk.HBox();
			this.hbox18.Name = "hbox18";
			this.hbox18.Spacing = 6;
			// Container child hbox18.Gtk.Box+BoxChild
			this.vbox16 = new global::Gtk.VBox();
			this.vbox16.Name = "vbox16";
			this.vbox16.Spacing = 6;
			// Container child vbox16.Gtk.Box+BoxChild
			this.vbox19 = new global::Gtk.VBox();
			this.vbox19.Name = "vbox19";
			this.vbox19.Spacing = 6;
			// Container child vbox19.Gtk.Box+BoxChild
			this.label22 = new global::Gtk.Label();
			this.label22.Name = "label22";
			this.label22.LabelProp = global::Mono.Unix.Catalog.GetString("ID usuario");
			this.vbox19.Add(this.label22);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox19[this.label22]));
			w29.Position = 0;
			w29.Fill = false;
			this.vbox16.Add(this.vbox19);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox16[this.vbox19]));
			w30.Position = 0;
			w30.Expand = false;
			w30.Fill = false;
			// Container child vbox16.Gtk.Box+BoxChild
			this.label23 = new global::Gtk.Label();
			this.label23.Name = "label23";
			this.label23.LabelProp = global::Mono.Unix.Catalog.GetString("Usuario");
			this.vbox16.Add(this.label23);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox16[this.label23]));
			w31.Position = 1;
			w31.Fill = false;
			// Container child vbox16.Gtk.Box+BoxChild
			this.label24 = new global::Gtk.Label();
			this.label24.Name = "label24";
			this.label24.LabelProp = global::Mono.Unix.Catalog.GetString("Rol");
			this.vbox16.Add(this.label24);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox16[this.label24]));
			w32.Position = 2;
			w32.Fill = false;
			// Container child vbox16.Gtk.Box+BoxChild
			this.button2 = new global::Gtk.Button();
			this.button2.CanFocus = true;
			this.button2.Name = "button2";
			this.button2.UseUnderline = true;
			this.button2.Label = global::Mono.Unix.Catalog.GetString("Nuevo");
			this.vbox16.Add(this.button2);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox16[this.button2]));
			w33.Position = 3;
			w33.Expand = false;
			w33.Fill = false;
			this.hbox18.Add(this.vbox16);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox18[this.vbox16]));
			w34.Position = 0;
			w34.Expand = false;
			w34.Fill = false;
			// Container child hbox18.Gtk.Box+BoxChild
			this.vbox17 = new global::Gtk.VBox();
			this.vbox17.Name = "vbox17";
			this.vbox17.Spacing = 6;
			// Container child vbox17.Gtk.Box+BoxChild
			this.vbox18 = new global::Gtk.VBox();
			this.vbox18.Name = "vbox18";
			this.vbox18.Spacing = 6;
			// Container child vbox18.Gtk.Box+BoxChild
			this.entry20 = new global::Gtk.Entry();
			this.entry20.CanFocus = true;
			this.entry20.Name = "entry20";
			this.entry20.IsEditable = true;
			this.entry20.InvisibleChar = '•';
			this.vbox18.Add(this.entry20);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox18[this.entry20]));
			w35.Position = 0;
			w35.Expand = false;
			w35.Fill = false;
			// Container child vbox18.Gtk.Box+BoxChild
			this.combobox1 = global::Gtk.ComboBox.NewText();
			this.combobox1.Name = "combobox1";
			this.vbox18.Add(this.combobox1);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox18[this.combobox1]));
			w36.Position = 1;
			w36.Expand = false;
			w36.Fill = false;
			this.vbox17.Add(this.vbox18);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox17[this.vbox18]));
			w37.Position = 0;
			w37.Expand = false;
			w37.Fill = false;
			// Container child vbox17.Gtk.Box+BoxChild
			this.combobox2 = global::Gtk.ComboBox.NewText();
			this.combobox2.Name = "combobox2";
			this.vbox17.Add(this.combobox2);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox17[this.combobox2]));
			w38.Position = 1;
			w38.Expand = false;
			w38.Fill = false;
			// Container child vbox17.Gtk.Box+BoxChild
			this.hbox20 = new global::Gtk.HBox();
			this.hbox20.Name = "hbox20";
			this.hbox20.Spacing = 6;
			// Container child hbox20.Gtk.Box+BoxChild
			this.button3 = new global::Gtk.Button();
			this.button3.CanFocus = true;
			this.button3.Name = "button3";
			this.button3.UseUnderline = true;
			this.button3.Label = global::Mono.Unix.Catalog.GetString("Agregar");
			this.hbox20.Add(this.button3);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.button3]));
			w39.Position = 0;
			w39.Expand = false;
			w39.Fill = false;
			// Container child hbox20.Gtk.Box+BoxChild
			this.button4 = new global::Gtk.Button();
			this.button4.CanFocus = true;
			this.button4.Name = "button4";
			this.button4.UseUnderline = true;
			this.button4.Label = global::Mono.Unix.Catalog.GetString("Modificar");
			this.hbox20.Add(this.button4);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.button4]));
			w40.Position = 1;
			w40.Expand = false;
			w40.Fill = false;
			this.vbox17.Add(this.hbox20);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox17[this.hbox20]));
			w41.Position = 2;
			w41.Expand = false;
			w41.Fill = false;
			this.hbox18.Add(this.vbox17);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox18[this.vbox17]));
			w42.Position = 1;
			w42.Expand = false;
			w42.Fill = false;
			// Container child hbox18.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeview4 = new global::Gtk.TreeView();
			this.treeview4.CanFocus = true;
			this.treeview4.Name = "treeview4";
			this.GtkScrolledWindow.Add(this.treeview4);
			this.hbox18.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.hbox18[this.GtkScrolledWindow]));
			w44.Position = 2;
			this.vbox15.Add(this.hbox18);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.vbox15[this.hbox18]));
			w45.Position = 1;
			w45.Expand = false;
			w45.Fill = false;
			this.Add(this.vbox15);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 718;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
