
// This file has been generated by the GUI designer. Do not modify.
namespace app_contable
{
	public partial class Gestionamiento_de_cuentas
	{
		private global::Gtk.Fixed fixed1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView treeview4;

		private global::Gtk.Label label30;

		private global::Gtk.Label label33;

		private global::Gtk.Entry entry15;

		private global::Gtk.Button button12;

		private global::Gtk.Label label27;

		private global::Gtk.Label label38;

		private global::Gtk.Entry entry10;

		private global::Gtk.Label label31;

		private global::Gtk.Label label29;

		private global::Gtk.Entry entry12;

		private global::Gtk.Entry entry11;

		private global::Gtk.Entry entry16;

		private global::Gtk.ComboBox combobox2;

		private global::Gtk.Label label32;

		private global::Gtk.Button button8;

		private global::Gtk.Button button7;

		private global::Gtk.Button button9;

		private global::Gtk.Entry entry14;

		private global::Gtk.Button button11;

		private global::Gtk.Label label37;

		private global::Gtk.Label label36;

		private global::Gtk.Button button10;

		private global::Gtk.Label label28;

		private global::Gtk.Label label35;

		private global::Gtk.Entry entry13;

		private global::Gtk.Entry entry9;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gtk.Label label34;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget app_contable.Gestionamiento_de_cuentas
			this.Name = "app_contable.Gestionamiento_de_cuentas";
			this.Title = global::Mono.Unix.Catalog.GetString("Gestionamiento de cuentas");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child app_contable.Gestionamiento_de_cuentas.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeview4 = new global::Gtk.TreeView();
			this.treeview4.WidthRequest = 525;
			this.treeview4.HeightRequest = 308;
			this.treeview4.CanFocus = true;
			this.treeview4.Name = "treeview4";
			this.GtkScrolledWindow.Add(this.treeview4);
			this.fixed1.Add(this.GtkScrolledWindow);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.GtkScrolledWindow]));
			w2.X = 430;
			w2.Y = 112;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label30 = new global::Gtk.Label();
			this.label30.Name = "label30";
			this.label30.LabelProp = global::Mono.Unix.Catalog.GetString("Pais");
			this.fixed1.Add(this.label30);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label30]));
			w3.X = 37;
			w3.Y = 321;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label33 = new global::Gtk.Label();
			this.label33.Name = "label33";
			this.label33.LabelProp = global::Mono.Unix.Catalog.GetString("ID de la cuenta");
			this.fixed1.Add(this.label33);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label33]));
			w4.X = 30;
			w4.Y = 105;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entry15 = new global::Gtk.Entry();
			this.entry15.CanFocus = true;
			this.entry15.Name = "entry15";
			this.entry15.IsEditable = true;
			this.entry15.InvisibleChar = '•';
			this.fixed1.Add(this.entry15);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.entry15]));
			w5.X = 792;
			w5.Y = 46;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button12 = new global::Gtk.Button();
			this.button12.CanFocus = true;
			this.button12.Name = "button12";
			this.button12.UseUnderline = true;
			this.button12.Label = global::Mono.Unix.Catalog.GetString("Buscar");
			this.fixed1.Add(this.button12);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button12]));
			w6.X = 955;
			w6.Y = 45;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label27 = new global::Gtk.Label();
			this.label27.Name = "label27";
			this.label27.LabelProp = global::Mono.Unix.Catalog.GetString("Datos de la cuenta");
			this.fixed1.Add(this.label27);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label27]));
			w7.X = 136;
			w7.Y = 43;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label38 = new global::Gtk.Label();
			this.label38.Name = "label38";
			this.label38.LabelProp = global::Mono.Unix.Catalog.GetString("Gestionamiento de Cuentas");
			this.fixed1.Add(this.label38);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label38]));
			w8.X = 479;
			w8.Y = 6;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entry10 = new global::Gtk.Entry();
			this.entry10.CanFocus = true;
			this.entry10.Name = "entry10";
			this.entry10.IsEditable = true;
			this.entry10.InvisibleChar = '•';
			this.fixed1.Add(this.entry10);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.entry10]));
			w9.X = 160;
			w9.Y = 141;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label31 = new global::Gtk.Label();
			this.label31.Name = "label31";
			this.label31.LabelProp = global::Mono.Unix.Catalog.GetString("Naturaleza");
			this.fixed1.Add(this.label31);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label31]));
			w10.X = 37;
			w10.Y = 389;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label29 = new global::Gtk.Label();
			this.label29.Name = "label29";
			this.label29.LabelProp = global::Mono.Unix.Catalog.GetString("Cuenta padre");
			this.fixed1.Add(this.label29);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label29]));
			w11.X = 37;
			w11.Y = 358;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entry12 = new global::Gtk.Entry();
			this.entry12.CanFocus = true;
			this.entry12.Name = "entry12";
			this.entry12.IsEditable = true;
			this.entry12.InvisibleChar = '•';
			this.fixed1.Add(this.entry12);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.entry12]));
			w12.X = 162;
			w12.Y = 315;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entry11 = new global::Gtk.Entry();
			this.entry11.CanFocus = true;
			this.entry11.Name = "entry11";
			this.entry11.IsEditable = true;
			this.entry11.InvisibleChar = '•';
			this.fixed1.Add(this.entry11);
			global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.entry11]));
			w13.X = 159;
			w13.Y = 353;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entry16 = new global::Gtk.Entry();
			this.entry16.CanFocus = true;
			this.entry16.Name = "entry16";
			this.entry16.IsEditable = true;
			this.entry16.InvisibleChar = '•';
			this.fixed1.Add(this.entry16);
			global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.entry16]));
			w14.X = 160;
			w14.Y = 389;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.combobox2 = global::Gtk.ComboBox.NewText();
			this.combobox2.AppendText(global::Mono.Unix.Catalog.GetString("Activa"));
			this.combobox2.AppendText(global::Mono.Unix.Catalog.GetString("Inactiva"));
			this.combobox2.WidthRequest = 154;
			this.combobox2.Name = "combobox2";
			this.fixed1.Add(this.combobox2);
			global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.combobox2]));
			w15.X = 164;
			w15.Y = 431;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label32 = new global::Gtk.Label();
			this.label32.Name = "label32";
			this.label32.LabelProp = global::Mono.Unix.Catalog.GetString("Estado");
			this.fixed1.Add(this.label32);
			global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label32]));
			w16.X = 38;
			w16.Y = 437;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button8 = new global::Gtk.Button();
			this.button8.WidthRequest = 72;
			this.button8.CanFocus = true;
			this.button8.Name = "button8";
			this.button8.UseUnderline = true;
			this.button8.Label = global::Mono.Unix.Catalog.GetString("Agregar");
			this.fixed1.Add(this.button8);
			global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button8]));
			w17.X = 335;
			w17.Y = 254;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button7 = new global::Gtk.Button();
			this.button7.WidthRequest = 72;
			this.button7.CanFocus = true;
			this.button7.Name = "button7";
			this.button7.UseUnderline = true;
			this.button7.Label = global::Mono.Unix.Catalog.GetString("Nuevo");
			this.fixed1.Add(this.button7);
			global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button7]));
			w18.X = 335;
			w18.Y = 204;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button9 = new global::Gtk.Button();
			this.button9.WidthRequest = 75;
			this.button9.CanFocus = true;
			this.button9.Name = "button9";
			this.button9.UseUnderline = true;
			this.button9.Label = global::Mono.Unix.Catalog.GetString("Modificar");
			this.fixed1.Add(this.button9);
			global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button9]));
			w19.X = 335;
			w19.Y = 309;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entry14 = new global::Gtk.Entry();
			this.entry14.CanFocus = true;
			this.entry14.Name = "entry14";
			this.entry14.IsEditable = true;
			this.entry14.InvisibleChar = '•';
			this.fixed1.Add(this.entry14);
			global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.entry14]));
			w20.X = 429;
			w20.Y = 47;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button11 = new global::Gtk.Button();
			this.button11.CanFocus = true;
			this.button11.Name = "button11";
			this.button11.UseUnderline = true;
			this.button11.Label = global::Mono.Unix.Catalog.GetString("Buscar");
			this.fixed1.Add(this.button11);
			global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button11]));
			w21.X = 589;
			w21.Y = 44;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label37 = new global::Gtk.Label();
			this.label37.Name = "label37";
			this.label37.LabelProp = global::Mono.Unix.Catalog.GetString("Buscar por nombre");
			this.fixed1.Add(this.label37);
			global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label37]));
			w22.X = 662;
			w22.Y = 49;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label36 = new global::Gtk.Label();
			this.label36.Name = "label36";
			this.label36.LabelProp = global::Mono.Unix.Catalog.GetString("Buscar por ID");
			this.fixed1.Add(this.label36);
			global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label36]));
			w23.X = 339;
			w23.Y = 51;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button10 = new global::Gtk.Button();
			this.button10.CanFocus = true;
			this.button10.Name = "button10";
			this.button10.UseUnderline = true;
			this.button10.Label = global::Mono.Unix.Catalog.GetString("Volver");
			this.fixed1.Add(this.button10);
			global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button10]));
			w24.X = 978;
			w24.Y = 3;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label28 = new global::Gtk.Label();
			this.label28.Name = "label28";
			this.label28.LabelProp = global::Mono.Unix.Catalog.GetString("Numero de la cuenta");
			this.fixed1.Add(this.label28);
			global::Gtk.Fixed.FixedChild w25 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label28]));
			w25.X = 9;
			w25.Y = 145;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label35 = new global::Gtk.Label();
			this.label35.Name = "label35";
			this.label35.LabelProp = global::Mono.Unix.Catalog.GetString("Nombre de la cuenta");
			this.fixed1.Add(this.label35);
			global::Gtk.Fixed.FixedChild w26 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label35]));
			w26.X = 9;
			w26.Y = 174;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entry13 = new global::Gtk.Entry();
			this.entry13.CanFocus = true;
			this.entry13.Name = "entry13";
			this.entry13.IsEditable = true;
			this.entry13.InvisibleChar = '•';
			this.fixed1.Add(this.entry13);
			global::Gtk.Fixed.FixedChild w27 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.entry13]));
			w27.X = 159;
			w27.Y = 174;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entry9 = new global::Gtk.Entry();
			this.entry9.CanFocus = true;
			this.entry9.Name = "entry9";
			this.entry9.IsEditable = true;
			this.entry9.InvisibleChar = '•';
			this.fixed1.Add(this.entry9);
			global::Gtk.Fixed.FixedChild w28 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.entry9]));
			w28.X = 161;
			w28.Y = 107;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow1.WidthRequest = 161;
			this.GtkScrolledWindow1.HeightRequest = 97;
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			this.fixed1.Add(this.GtkScrolledWindow1);
			global::Gtk.Fixed.FixedChild w29 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.GtkScrolledWindow1]));
			w29.X = 160;
			w29.Y = 205;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label34 = new global::Gtk.Label();
			this.label34.Name = "label34";
			this.label34.LabelProp = global::Mono.Unix.Catalog.GetString("Descripción");
			this.fixed1.Add(this.label34);
			global::Gtk.Fixed.FixedChild w30 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label34]));
			w30.X = 37;
			w30.Y = 230;
			this.Add(this.fixed1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 1037;
			this.DefaultHeight = 485;
			this.Show();
		}
	}
}
