
// This file has been generated by the GUI designer. Do not modify.
namespace app_contable
{
	public partial class Gestionamiento_de_asientos_contables
	{
		private global::Gtk.HBox hbox30;

		private global::Gtk.VBox vbox21;

		private global::Gtk.VBox vbox29;

		private global::Gtk.HBox hbox37;

		private global::Gtk.HBox hbox39;

		private global::Gtk.Label label54;

		private global::Gtk.Alignment alignment24;

		private global::Gtk.Alignment alignment25;

		private global::Gtk.Alignment alignment23;

		private global::Gtk.Button button13;

		private global::Gtk.HBox hbox38;

		private global::Gtk.Label label53;

		private global::Gtk.Alignment alignment21;

		private global::Gtk.Alignment alignment20;

		private global::Gtk.HBox hbox31;

		private global::Gtk.HBox hbox35;

		private global::Gtk.VBox vbox25;

		private global::Gtk.VBox vbox26;

		private global::Gtk.Label label44;

		private global::Gtk.Label label35;

		private global::Gtk.Label label48;

		private global::Gtk.Label label46;

		private global::Gtk.VBox vbox27;

		private global::Gtk.Label label45;

		private global::Gtk.Label label39;

		private global::Gtk.VBox vbox28;

		private global::Gtk.Label label40;

		private global::Gtk.Alignment alignment16;

		private global::Gtk.Label label42;

		private global::Gtk.VBox vbox24;

		private global::Gtk.VBox vbox31;

		private global::Gtk.Entry entry23;

		private global::Gtk.Entry entry24;

		private global::Gtk.Entry entry25;

		private global::Gtk.VBox vbox30;

		private global::Gtk.Entry entry26;

		private global::Gtk.Entry entry27;

		private global::Gtk.VBox vbox32;

		private global::Gtk.Entry entry28;

		private global::Gtk.Entry entry29;

		private global::Gtk.ComboBox combobox3;

		private global::Gtk.VBox vbox33;

		private global::Gtk.VBox vbox34;

		private global::Gtk.Alignment alignment14;

		private global::Gtk.Alignment alignment17;

		private global::Gtk.Alignment alignment19;

		private global::Gtk.VBox vbox35;

		private global::Gtk.Button button8;

		private global::Gtk.Button button9;

		private global::Gtk.Button button10;

		private global::Gtk.Alignment alignment15;

		private global::Gtk.Alignment alignment18;

		private global::Gtk.VBox vbox23;

		private global::Gtk.HBox hbox32;

		private global::Gtk.Label label51;

		private global::Gtk.HBox hbox34;

		private global::Gtk.Entry entry30;

		private global::Gtk.Button button11;

		private global::Gtk.HBox hbox33;

		private global::Gtk.Label label52;

		private global::Gtk.Entry entry31;

		private global::Gtk.Button button12;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView treeview5;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget app_contable.Gestionamiento_de_asientos_contables
			this.Name = "app_contable.Gestionamiento_de_asientos_contables";
			this.Title = global::Mono.Unix.Catalog.GetString("Gestionamiento de asientos contables");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child app_contable.Gestionamiento_de_asientos_contables.Gtk.Container+ContainerChild
			this.hbox30 = new global::Gtk.HBox();
			this.hbox30.Name = "hbox30";
			this.hbox30.Spacing = 6;
			// Container child hbox30.Gtk.Box+BoxChild
			this.vbox21 = new global::Gtk.VBox();
			this.vbox21.Name = "vbox21";
			this.vbox21.Spacing = 6;
			// Container child vbox21.Gtk.Box+BoxChild
			this.vbox29 = new global::Gtk.VBox();
			this.vbox29.Name = "vbox29";
			this.vbox29.Spacing = 6;
			// Container child vbox29.Gtk.Box+BoxChild
			this.hbox37 = new global::Gtk.HBox();
			this.hbox37.Name = "hbox37";
			this.hbox37.Spacing = 6;
			// Container child hbox37.Gtk.Box+BoxChild
			this.hbox39 = new global::Gtk.HBox();
			this.hbox39.Name = "hbox39";
			this.hbox39.Spacing = 6;
			// Container child hbox39.Gtk.Box+BoxChild
			this.label54 = new global::Gtk.Label();
			this.label54.Name = "label54";
			this.label54.LabelProp = global::Mono.Unix.Catalog.GetString("Gestionamiento de asientos contables");
			this.hbox39.Add(this.label54);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox39[this.label54]));
			w1.Position = 2;
			w1.Expand = false;
			w1.Fill = false;
			this.hbox37.Add(this.hbox39);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox37[this.hbox39]));
			w2.Position = 0;
			// Container child hbox37.Gtk.Box+BoxChild
			this.alignment24 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment24.Name = "alignment24";
			// Container child alignment24.Gtk.Container+ContainerChild
			this.alignment25 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment25.Name = "alignment25";
			this.alignment24.Add(this.alignment25);
			this.hbox37.Add(this.alignment24);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox37[this.alignment24]));
			w4.Position = 1;
			// Container child hbox37.Gtk.Box+BoxChild
			this.alignment23 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment23.Name = "alignment23";
			// Container child alignment23.Gtk.Container+ContainerChild
			this.button13 = new global::Gtk.Button();
			this.button13.CanFocus = true;
			this.button13.Name = "button13";
			this.button13.UseUnderline = true;
			this.button13.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
			this.alignment23.Add(this.button13);
			this.hbox37.Add(this.alignment23);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox37[this.alignment23]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			this.vbox29.Add(this.hbox37);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox29[this.hbox37]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox29.Gtk.Box+BoxChild
			this.hbox38 = new global::Gtk.HBox();
			this.hbox38.Name = "hbox38";
			this.hbox38.Spacing = 6;
			// Container child hbox38.Gtk.Box+BoxChild
			this.label53 = new global::Gtk.Label();
			this.label53.Name = "label53";
			this.label53.LabelProp = global::Mono.Unix.Catalog.GetString("Datos del siento contable");
			this.hbox38.Add(this.label53);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox38[this.label53]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox38.Gtk.Box+BoxChild
			this.alignment21 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment21.Name = "alignment21";
			this.hbox38.Add(this.alignment21);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox38[this.alignment21]));
			w9.Position = 1;
			// Container child hbox38.Gtk.Box+BoxChild
			this.alignment20 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment20.Name = "alignment20";
			this.hbox38.Add(this.alignment20);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox38[this.alignment20]));
			w10.Position = 2;
			this.vbox29.Add(this.hbox38);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox29[this.hbox38]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			this.vbox21.Add(this.vbox29);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox21[this.vbox29]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox21.Gtk.Box+BoxChild
			this.hbox31 = new global::Gtk.HBox();
			this.hbox31.Name = "hbox31";
			this.hbox31.Spacing = 6;
			// Container child hbox31.Gtk.Box+BoxChild
			this.hbox35 = new global::Gtk.HBox();
			this.hbox35.Name = "hbox35";
			this.hbox35.Spacing = 6;
			// Container child hbox35.Gtk.Box+BoxChild
			this.vbox25 = new global::Gtk.VBox();
			this.vbox25.Name = "vbox25";
			this.vbox25.Spacing = 6;
			// Container child vbox25.Gtk.Box+BoxChild
			this.vbox26 = new global::Gtk.VBox();
			this.vbox26.Name = "vbox26";
			this.vbox26.Spacing = 6;
			// Container child vbox26.Gtk.Box+BoxChild
			this.label44 = new global::Gtk.Label();
			this.label44.Name = "label44";
			this.label44.LabelProp = global::Mono.Unix.Catalog.GetString("ID del asiento");
			this.vbox26.Add(this.label44);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox26[this.label44]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox26.Gtk.Box+BoxChild
			this.label35 = new global::Gtk.Label();
			this.label35.Name = "label35";
			this.label35.LabelProp = global::Mono.Unix.Catalog.GetString("ID de la cuenta");
			this.vbox26.Add(this.label35);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox26[this.label35]));
			w14.Position = 2;
			w14.Expand = false;
			w14.Fill = false;
			this.vbox25.Add(this.vbox26);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox25[this.vbox26]));
			w15.Position = 0;
			// Container child vbox25.Gtk.Box+BoxChild
			this.label48 = new global::Gtk.Label();
			this.label48.Name = "label48";
			this.label48.LabelProp = global::Mono.Unix.Catalog.GetString("Codigo del asiento");
			this.vbox25.Add(this.label48);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox25[this.label48]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox25.Gtk.Box+BoxChild
			this.label46 = new global::Gtk.Label();
			this.label46.Name = "label46";
			this.label46.LabelProp = global::Mono.Unix.Catalog.GetString("Numero de la cuenta debe");
			this.vbox25.Add(this.label46);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox25[this.label46]));
			w17.Position = 2;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox25.Gtk.Box+BoxChild
			this.vbox27 = new global::Gtk.VBox();
			this.vbox27.Name = "vbox27";
			this.vbox27.Spacing = 6;
			// Container child vbox27.Gtk.Box+BoxChild
			this.label45 = new global::Gtk.Label();
			this.label45.Name = "label45";
			this.label45.LabelProp = global::Mono.Unix.Catalog.GetString("Importe del debe");
			this.vbox27.Add(this.label45);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox27[this.label45]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			// Container child vbox27.Gtk.Box+BoxChild
			this.label39 = new global::Gtk.Label();
			this.label39.Name = "label39";
			this.label39.LabelProp = global::Mono.Unix.Catalog.GetString("Numero de la cuenta haber");
			this.vbox27.Add(this.label39);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox27[this.label39]));
			w19.Position = 2;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vbox27.Gtk.Box+BoxChild
			this.vbox28 = new global::Gtk.VBox();
			this.vbox28.Name = "vbox28";
			this.vbox28.Spacing = 6;
			// Container child vbox28.Gtk.Box+BoxChild
			this.label40 = new global::Gtk.Label();
			this.label40.Name = "label40";
			this.label40.LabelProp = global::Mono.Unix.Catalog.GetString("Importe del haber");
			this.vbox28.Add(this.label40);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox28[this.label40]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox28.Gtk.Box+BoxChild
			this.alignment16 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment16.Name = "alignment16";
			this.vbox28.Add(this.alignment16);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox28[this.alignment16]));
			w21.Position = 2;
			// Container child vbox28.Gtk.Box+BoxChild
			this.label42 = new global::Gtk.Label();
			this.label42.Name = "label42";
			this.label42.LabelProp = global::Mono.Unix.Catalog.GetString("Estado");
			this.vbox28.Add(this.label42);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox28[this.label42]));
			w22.Position = 3;
			w22.Expand = false;
			w22.Fill = false;
			this.vbox27.Add(this.vbox28);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox27[this.vbox28]));
			w23.Position = 3;
			this.vbox25.Add(this.vbox27);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox25[this.vbox27]));
			w24.Position = 3;
			this.hbox35.Add(this.vbox25);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox35[this.vbox25]));
			w25.Position = 0;
			w25.Expand = false;
			w25.Fill = false;
			// Container child hbox35.Gtk.Box+BoxChild
			this.vbox24 = new global::Gtk.VBox();
			this.vbox24.Name = "vbox24";
			this.vbox24.Spacing = 6;
			// Container child vbox24.Gtk.Box+BoxChild
			this.vbox31 = new global::Gtk.VBox();
			this.vbox31.Name = "vbox31";
			this.vbox31.Spacing = 6;
			// Container child vbox31.Gtk.Box+BoxChild
			this.entry23 = new global::Gtk.Entry();
			this.entry23.CanFocus = true;
			this.entry23.Name = "entry23";
			this.entry23.IsEditable = true;
			this.entry23.InvisibleChar = '•';
			this.vbox31.Add(this.entry23);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox31[this.entry23]));
			w26.Position = 0;
			w26.Expand = false;
			w26.Fill = false;
			// Container child vbox31.Gtk.Box+BoxChild
			this.entry24 = new global::Gtk.Entry();
			this.entry24.CanFocus = true;
			this.entry24.Name = "entry24";
			this.entry24.IsEditable = true;
			this.entry24.InvisibleChar = '•';
			this.vbox31.Add(this.entry24);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox31[this.entry24]));
			w27.Position = 1;
			w27.Expand = false;
			w27.Fill = false;
			// Container child vbox31.Gtk.Box+BoxChild
			this.entry25 = new global::Gtk.Entry();
			this.entry25.CanFocus = true;
			this.entry25.Name = "entry25";
			this.entry25.IsEditable = true;
			this.entry25.InvisibleChar = '•';
			this.vbox31.Add(this.entry25);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox31[this.entry25]));
			w28.Position = 2;
			w28.Expand = false;
			w28.Fill = false;
			this.vbox24.Add(this.vbox31);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox24[this.vbox31]));
			w29.Position = 0;
			w29.Expand = false;
			w29.Fill = false;
			// Container child vbox24.Gtk.Box+BoxChild
			this.vbox30 = new global::Gtk.VBox();
			this.vbox30.Name = "vbox30";
			this.vbox30.Spacing = 6;
			// Container child vbox30.Gtk.Box+BoxChild
			this.entry26 = new global::Gtk.Entry();
			this.entry26.CanFocus = true;
			this.entry26.Name = "entry26";
			this.entry26.IsEditable = true;
			this.entry26.InvisibleChar = '•';
			this.vbox30.Add(this.entry26);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox30[this.entry26]));
			w30.Position = 0;
			w30.Expand = false;
			w30.Fill = false;
			// Container child vbox30.Gtk.Box+BoxChild
			this.entry27 = new global::Gtk.Entry();
			this.entry27.CanFocus = true;
			this.entry27.Name = "entry27";
			this.entry27.IsEditable = true;
			this.entry27.InvisibleChar = '•';
			this.vbox30.Add(this.entry27);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox30[this.entry27]));
			w31.Position = 1;
			w31.Expand = false;
			w31.Fill = false;
			this.vbox24.Add(this.vbox30);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox24[this.vbox30]));
			w32.Position = 1;
			w32.Expand = false;
			w32.Fill = false;
			// Container child vbox24.Gtk.Box+BoxChild
			this.vbox32 = new global::Gtk.VBox();
			this.vbox32.Name = "vbox32";
			this.vbox32.Spacing = 6;
			// Container child vbox32.Gtk.Box+BoxChild
			this.entry28 = new global::Gtk.Entry();
			this.entry28.CanFocus = true;
			this.entry28.Name = "entry28";
			this.entry28.IsEditable = true;
			this.entry28.InvisibleChar = '•';
			this.vbox32.Add(this.entry28);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox32[this.entry28]));
			w33.Position = 0;
			w33.Expand = false;
			w33.Fill = false;
			// Container child vbox32.Gtk.Box+BoxChild
			this.entry29 = new global::Gtk.Entry();
			this.entry29.CanFocus = true;
			this.entry29.Name = "entry29";
			this.entry29.IsEditable = true;
			this.entry29.InvisibleChar = '•';
			this.vbox32.Add(this.entry29);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox32[this.entry29]));
			w34.Position = 1;
			w34.Expand = false;
			w34.Fill = false;
			// Container child vbox32.Gtk.Box+BoxChild
			this.combobox3 = global::Gtk.ComboBox.NewText();
			this.combobox3.Name = "combobox3";
			this.vbox32.Add(this.combobox3);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox32[this.combobox3]));
			w35.Position = 2;
			w35.Expand = false;
			w35.Fill = false;
			this.vbox24.Add(this.vbox32);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox24[this.vbox32]));
			w36.Position = 2;
			w36.Expand = false;
			w36.Fill = false;
			this.hbox35.Add(this.vbox24);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox35[this.vbox24]));
			w37.Position = 1;
			w37.Expand = false;
			w37.Fill = false;
			this.hbox31.Add(this.hbox35);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox31[this.hbox35]));
			w38.Position = 0;
			w38.Expand = false;
			w38.Fill = false;
			// Container child hbox31.Gtk.Box+BoxChild
			this.vbox33 = new global::Gtk.VBox();
			this.vbox33.Name = "vbox33";
			this.vbox33.Spacing = 6;
			// Container child vbox33.Gtk.Box+BoxChild
			this.vbox34 = new global::Gtk.VBox();
			this.vbox34.Name = "vbox34";
			this.vbox34.Spacing = 6;
			// Container child vbox34.Gtk.Box+BoxChild
			this.alignment14 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment14.Name = "alignment14";
			// Container child alignment14.Gtk.Container+ContainerChild
			this.alignment17 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment17.Name = "alignment17";
			// Container child alignment17.Gtk.Container+ContainerChild
			this.alignment19 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment19.Name = "alignment19";
			this.alignment17.Add(this.alignment19);
			this.alignment14.Add(this.alignment17);
			this.vbox34.Add(this.alignment14);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox34[this.alignment14]));
			w41.Position = 0;
			this.vbox33.Add(this.vbox34);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.vbox33[this.vbox34]));
			w42.Position = 0;
			// Container child vbox33.Gtk.Box+BoxChild
			this.vbox35 = new global::Gtk.VBox();
			this.vbox35.Name = "vbox35";
			this.vbox35.Spacing = 6;
			// Container child vbox35.Gtk.Box+BoxChild
			this.button8 = new global::Gtk.Button();
			this.button8.CanFocus = true;
			this.button8.Name = "button8";
			this.button8.UseUnderline = true;
			this.button8.Label = global::Mono.Unix.Catalog.GetString("Nuevo");
			this.vbox35.Add(this.button8);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox35[this.button8]));
			w43.Position = 0;
			w43.Expand = false;
			w43.Fill = false;
			// Container child vbox35.Gtk.Box+BoxChild
			this.button9 = new global::Gtk.Button();
			this.button9.CanFocus = true;
			this.button9.Name = "button9";
			this.button9.UseUnderline = true;
			this.button9.Label = global::Mono.Unix.Catalog.GetString("Agregar");
			this.vbox35.Add(this.button9);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vbox35[this.button9]));
			w44.Position = 1;
			w44.Expand = false;
			w44.Fill = false;
			// Container child vbox35.Gtk.Box+BoxChild
			this.button10 = new global::Gtk.Button();
			this.button10.CanFocus = true;
			this.button10.Name = "button10";
			this.button10.UseUnderline = true;
			this.button10.Label = global::Mono.Unix.Catalog.GetString("Modificar");
			this.vbox35.Add(this.button10);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.vbox35[this.button10]));
			w45.Position = 2;
			w45.Expand = false;
			w45.Fill = false;
			this.vbox33.Add(this.vbox35);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.vbox33[this.vbox35]));
			w46.Position = 1;
			w46.Expand = false;
			w46.Fill = false;
			// Container child vbox33.Gtk.Box+BoxChild
			this.alignment15 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment15.Name = "alignment15";
			// Container child alignment15.Gtk.Container+ContainerChild
			this.alignment18 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment18.Name = "alignment18";
			this.alignment15.Add(this.alignment18);
			this.vbox33.Add(this.alignment15);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.vbox33[this.alignment15]));
			w48.Position = 2;
			this.hbox31.Add(this.vbox33);
			global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.hbox31[this.vbox33]));
			w49.Position = 1;
			w49.Expand = false;
			w49.Fill = false;
			// Container child hbox31.Gtk.Box+BoxChild
			this.vbox23 = new global::Gtk.VBox();
			this.vbox23.Name = "vbox23";
			this.vbox23.Spacing = 6;
			// Container child vbox23.Gtk.Box+BoxChild
			this.hbox32 = new global::Gtk.HBox();
			this.hbox32.Name = "hbox32";
			this.hbox32.Spacing = 6;
			// Container child hbox32.Gtk.Box+BoxChild
			this.label51 = new global::Gtk.Label();
			this.label51.Name = "label51";
			this.label51.LabelProp = global::Mono.Unix.Catalog.GetString("Buscar por ID");
			this.hbox32.Add(this.label51);
			global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.hbox32[this.label51]));
			w50.Position = 0;
			w50.Expand = false;
			w50.Fill = false;
			// Container child hbox32.Gtk.Box+BoxChild
			this.hbox34 = new global::Gtk.HBox();
			this.hbox34.Name = "hbox34";
			this.hbox34.Spacing = 6;
			// Container child hbox34.Gtk.Box+BoxChild
			this.entry30 = new global::Gtk.Entry();
			this.entry30.CanFocus = true;
			this.entry30.Name = "entry30";
			this.entry30.IsEditable = true;
			this.entry30.InvisibleChar = '•';
			this.hbox34.Add(this.entry30);
			global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.hbox34[this.entry30]));
			w51.Position = 0;
			// Container child hbox34.Gtk.Box+BoxChild
			this.button11 = new global::Gtk.Button();
			this.button11.CanFocus = true;
			this.button11.Name = "button11";
			this.button11.UseUnderline = true;
			this.button11.Label = global::Mono.Unix.Catalog.GetString("Buscar");
			this.hbox34.Add(this.button11);
			global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.hbox34[this.button11]));
			w52.Position = 1;
			w52.Expand = false;
			w52.Fill = false;
			this.hbox32.Add(this.hbox34);
			global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.hbox32[this.hbox34]));
			w53.Position = 1;
			// Container child hbox32.Gtk.Box+BoxChild
			this.hbox33 = new global::Gtk.HBox();
			this.hbox33.Name = "hbox33";
			this.hbox33.Spacing = 6;
			// Container child hbox33.Gtk.Box+BoxChild
			this.label52 = new global::Gtk.Label();
			this.label52.Name = "label52";
			this.label52.LabelProp = global::Mono.Unix.Catalog.GetString("Buscar por código");
			this.hbox33.Add(this.label52);
			global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.hbox33[this.label52]));
			w54.Position = 0;
			w54.Expand = false;
			w54.Fill = false;
			// Container child hbox33.Gtk.Box+BoxChild
			this.entry31 = new global::Gtk.Entry();
			this.entry31.CanFocus = true;
			this.entry31.Name = "entry31";
			this.entry31.IsEditable = true;
			this.entry31.InvisibleChar = '•';
			this.hbox33.Add(this.entry31);
			global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.hbox33[this.entry31]));
			w55.Position = 1;
			// Container child hbox33.Gtk.Box+BoxChild
			this.button12 = new global::Gtk.Button();
			this.button12.CanFocus = true;
			this.button12.Name = "button12";
			this.button12.UseUnderline = true;
			this.button12.Label = global::Mono.Unix.Catalog.GetString("Buscar");
			this.hbox33.Add(this.button12);
			global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.hbox33[this.button12]));
			w56.Position = 2;
			w56.Expand = false;
			w56.Fill = false;
			this.hbox32.Add(this.hbox33);
			global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.hbox32[this.hbox33]));
			w57.Position = 2;
			this.vbox23.Add(this.hbox32);
			global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.vbox23[this.hbox32]));
			w58.Position = 0;
			w58.Expand = false;
			w58.Fill = false;
			// Container child vbox23.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeview5 = new global::Gtk.TreeView();
			this.treeview5.CanFocus = true;
			this.treeview5.Name = "treeview5";
			this.GtkScrolledWindow.Add(this.treeview5);
			this.vbox23.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.vbox23[this.GtkScrolledWindow]));
			w60.Position = 1;
			this.hbox31.Add(this.vbox23);
			global::Gtk.Box.BoxChild w61 = ((global::Gtk.Box.BoxChild)(this.hbox31[this.vbox23]));
			w61.Position = 2;
			this.vbox21.Add(this.hbox31);
			global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.vbox21[this.hbox31]));
			w62.Position = 1;
			w62.Expand = false;
			w62.Fill = false;
			this.hbox30.Add(this.vbox21);
			global::Gtk.Box.BoxChild w63 = ((global::Gtk.Box.BoxChild)(this.hbox30[this.vbox21]));
			w63.Position = 0;
			this.Add(this.hbox30);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 1159;
			this.DefaultHeight = 383;
			this.Show();
		}
	}
}
