
// This file has been generated by the GUI designer. Do not modify.
namespace app_contable
{
	public partial class Balance_General
	{
		private global::Gtk.Fixed fixed1;

		private global::Gtk.Calendar calendar1;

		private global::Gtk.Label label2;

		private global::Gtk.Calendar calendar2;

		private global::Gtk.Label label3;

		private global::Gtk.Button button1;

		private global::Gtk.Button button2;

		private global::Gtk.Label label1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget app_contable.Balance_General
			this.Name = "app_contable.Balance_General";
			this.Title = global::Mono.Unix.Catalog.GetString("Balance General");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child app_contable.Balance_General.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.calendar1 = new global::Gtk.Calendar();
			this.calendar1.CanFocus = true;
			this.calendar1.Name = "calendar1";
			this.calendar1.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
			this.fixed1.Add(this.calendar1);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.calendar1]));
			w1.X = 34;
			w1.Y = 102;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Fecha de inicio");
			this.fixed1.Add(this.label2);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label2]));
			w2.X = 110;
			w2.Y = 71;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.calendar2 = new global::Gtk.Calendar();
			this.calendar2.CanFocus = true;
			this.calendar2.Name = "calendar2";
			this.calendar2.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
			this.fixed1.Add(this.calendar2);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.calendar2]));
			w3.X = 416;
			w3.Y = 100;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Fecha de finalizacion");
			this.fixed1.Add(this.label3);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label3]));
			w4.X = 480;
			w4.Y = 77;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button1 = new global::Gtk.Button();
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			this.button1.Label = global::Mono.Unix.Catalog.GetString("Volver");
			this.fixed1.Add(this.button1);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button1]));
			w5.X = 619;
			w5.Y = 6;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button2 = new global::Gtk.Button();
			this.button2.CanFocus = true;
			this.button2.Name = "button2";
			this.button2.UseUnderline = true;
			this.button2.Label = global::Mono.Unix.Catalog.GetString("Generar");
			this.fixed1.Add(this.button2);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button2]));
			w6.X = 327;
			w6.Y = 314;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Balance general");
			this.fixed1.Add(this.label1);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label1]));
			w7.X = 309;
			w7.Y = 36;
			this.Add(this.fixed1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 695;
			this.DefaultHeight = 361;
			this.Show();
		}
	}
}
